context:
  version: "0.2.1"
  python_min: "3.11"

package:
  name: optiwindnet
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/o/optiwindnet/optiwindnet-${{ version }}.tar.gz
  sha256: c573a79aa02634c9704ed8388f63ae6268282a49e6811a2f4b81b9d30bca6387

build:
  number: 0
  noarch: python
  script: python -m pip install . --no-deps -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=80
    - setuptools-scm >=8
  run:
    - python >=${{ python_min }}
    - bidict >=0.23.1
    - bitarray >=3.4.2
    - condeltri >=0.0.3
    - darkdetect >=0.8.0
    - esy.osm.pbf >=0.1.1
    - hybgensea >=0.1.1
    - makefun >=1.15.6
    - matplotlib-base >=3.10.1
    - networkx >=3.6
    - numba >=0.62.1
    - numpy >=2.0
    - peewee >=3.17
    - pyomo >=6.9.5
    - pyyaml >=6.0.2
    - pyyaml-include >=2.1
    - scipy >=1.15.2
    - shapely >=2.0.7
    - svg.py >=1.6.0
    - utm >=0.7.0
    - highspy >=1.12

tests:
  - python:
      imports:
        - optiwindnet.api
      # pip_check complains about the lack of ortools (dependency in pyproject.toml)
      # ortools-python from conda-forge is stuck on version 9.6 for 2+ years
      # discussion at https://github.com/conda-forge/or-tools-feedstock/pull/47
      pip_check: false
  - script:
      - pytest tests/ --ignore=tests/test_MILP.py
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - pytest-cov
        - coverage
        - psutil
        - memory_profiler
        - line_profiler
        - coin-or-cbc
        - pyscipopt
    files:  
      source:
        - tests/      
        - .coveragerc

about:
  homepage: https://optiwindnet.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: "Tool for designing and optimizing the electrical cable network of offshore wind farms"
  description: |
    OptiWindNet is an electrical network design tool for offshore wind farms developed at the Technical
    University of Denmark – DTU. The package offers a framework to obtain optimal or near-optimal cable
    routes for a given turbine layout within the cable-laying boundaries. It provides high-level access
    to heuristic, meta-heuristic and mathematical optimization approaches to the problem.
  documentation: https://optiwindnet.readthedocs.io/
  repository: https://gitlab.windenergy.dtu.dk/TOPFARM/OptiWindNet

extra:
  recipe-maintainers:
    - mdealencar
    - simutisernestas
